---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: iam-policy
  namespace: flux-system
spec:
  path: ./terraform
  approvePlan: auto
  interval: 2m
  varsFrom:
    kind: Secret
    name: aws-credentials
  sourceRef:
    kind: GitRepository
    name: aws-ec2
    namespace: flux-system
